In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pandas_profiling as pp
import warnings
warnings.filterwarnings('ignore')

In [8]:
df = pd.read_csv('Ericsson_Data.tar49135d9.gz', compression='gzip', encoding= 'ISO-8859-1')

C:\Users\M1049810\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df

,train_file.csv,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,overall,score_1,score_2,score_3,score_4,score_5,score_6
0,1.0,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,5,4,5,5,4,5,0.0
1,5.0,startup_1,"Los Angeles, CA","Jul 19, 2018",Former Employee,Software Engineer,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...",Promote managers into management for their man...,5,5,5,5,5,5,49.0
2,9.0,startup_1,"New York, NY","Dec 10, 2018",Current Employee,Anonymous Employee,Google Surpasses Realistic Expectations,Great products. Vision you can feel good about...,Younger employees complaining about the compan...,NaN,5,5,5,5,5,5,0.0
3,16.0,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,Review,The people are great to work with,There is lower compensation than expected,NaN,5,NaN,NaN,NaN,NaN,NaN,0.0
4,17.0,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Review of Google,"The people are great to work with, good perks.",Wide variety in experience based on team.,NaN,5,4,5,5,5,4,2.0
5,18.0,startup_1,NaN,"Dec 2, 2018",Former Employee,Anonymous Employee,Analysts,"Good managers, benefits , some support, nice a...","Long hours, far locations, a lot of work",NaN,5,NaN,NaN,2,NaN,NaN,1.0
6,19.0,startup_1,NaN,"Dec 1, 2018",Former Employee,Anonymous Employee,Great Company With No Down Sides,Really fun work environment with startup,Really no down sides that I saw.,NaN,5,5,5,5,5,5,1.0
7,21.0,startup_1,"New York, NY","Nov 26, 2018",Current Employee,Designer,"Great, but great can always be better",Great team and support for individuals,"Lots of bureaucracy, not super diverse",NaN,5,3,4,3,4,5,2.0
8,22.0,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,Great company to work for,I love Google a lot,Some things are not to great,NaN,5,5,5,5,5,5,0.0
9,23.0,startup_1,NaN,"Dec 1, 2018",Current Employee,Anonymous Employee,NaN,it's a great place to work!,too much red tape on doing even the smallest p...,NaN,5,NaN,NaN,5,NaN,NaN,0.0
10,24.0,startup_1,NaN,"Nov 30, 2018",Current Employee,Anonymous Employee,Software Engineer,Awesome job environment to work in,Pressure is there for some parts,NaN,5,NaN,NaN,NaN,NaN,NaN,0.0
11,25.0,startup_1,"Los Angeles, CA","Nov 29, 2018",Current Employee,Staff Accountant,Accountant,I like and learned from the beginning accounting,High clerical work in the Sane record,Management and Finance must be close relation ...,5,5,5,5,5,5,0.0
12,26.0,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Good Company to Work for,"- perks are phenomenal, food, health, office",- work life balance is hard to manage,NaN,5,4,5,4,5,5,0.0
13,29.0,startup_1,NaN,"Nov 27, 2018",Current Employee,Anonymous Employee,Great place to work,The people are awesome. Lots of perks. Reduce ...,There's sometimes too wide a variety of things...,NaN,5,4,5,5,5,5,0.0
14,30.0,startup_1,NaN,"Nov 20, 2018",Former Employee,Anonymous Employee,Great,"Great place to work, free food, and great cult...","Big company, prepare to move much slower than ...",NaN,5,NaN,NaN,NaN,NaN,NaN,2.0
15,33.0,startup_1,NaN,"Nov 24, 2018",Current Employee,Anonymous Employee,Is very good,is very good. is very very good,You work a lot. Like a lot,NaN,5,5,5,5,5,5,0.0
16,34.0,startup_1,"Mountain View, CA","Dec 8, 2018",Current Employee,Software Engineering Manager,Google is still the best place to be,"Great place to work, learn new things, grow an...",Large company issues have crept up but nothing...,NaN,4,5,5,4,4,4,0.0
17,35.0,startup_1,"Dearborn, MI","Nov 20, 2018",Current Employee,Google Specialist,Google,Google is one of the beast Company in the world,You have to work hard,NaN,5,3,4,4,5,4,1.0
18,36.0,startup_1,NaN,"Nov 19, 2018",Current Employee,Anonymous Employee,Good place to work,Nice perks. Good work life balance,too slow and too much consensus culture someti...,NaN,5,5,5,5,5,5,1.0
19,38.0,startup_1,"New York, NY","Dec 6, 2018",Current Employee,Anonymous Employee,Good compensation,Better than average engineers. Competitive com...,Big and beurocratic. Lots of legacy systems. M...,NaN,4,4,3,3,4,3,0.0
20,39.0,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,"Great perks, bad work-life balance","Googleâs perks are great: free food, shuttle...",I have zero work-life balance. I work minimum ...,Restructure performance reviews so that some f...,3,2,3,5,5,3,0.0
21,40.0,startup_1,"Sunnyvale, CA","Nov 21, 2018",Current Employee,Anonymous Employee,Best of the best,"The best company I've worked for. Culture, per...","Set hours for breakfast, lunch, dinner.",NaN,5,3,5,5,5,4,0.0
22,42.0,startup_1,"Seattle, WA","Nov 13, 2018",Current Employee,Staff Software Engineer,Hard to beat,Amazing compensation + benefits (hard to beat ...,Growing pains as Google has gone from ~10k to ...,NaN,5,4,4,5,5,3,2.0
23,43.0,startup_1,NaN,"Dec 4, 2018",Former Employee,Anonymous Employee,Big Tech,Never have to skip a paycheck.,Google has an over abundance of technicians an...,NaN,3,3,2,3,4,1,0.0
24,45.0,startup_1,"Sunnyvale, CA","Nov 19, 2018",Current Employee,Software Engineer,Positive Experiences,Good opportunities for different technical exp...,Difficult to advance depending on which projec...,NaN,5,5,5,4,4,4,0.0
25,48.0,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,Its Google,"food, shuttle, technology, perks, health, 401K...",Great place to work finace is backend though. ...,NaN,4,4,4,4,4,3,0.0
26,49.0,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,g,"perks are pretty good, as is culture",work/life balance is generally moderate to poor,NaN,4,2,4,4,5,4,0.0
27,51.0,startup_1,NaN,"Nov 15, 2018",Current Employee,Anonymous Employee,Good place,Pretty good benifits and bank.,Being challanged everyday. Having no life.,NaN,5,NaN,NaN,5,NaN,NaN,0.0
28,52.0,startup_1,NaN,"Nov 27, 2018",Former Employee,Anonymous Employee,cs analyst,"great work culture , good for starters",long hours can be unreasonable,"none, doing fantastic",4,NaN,NaN,NaN,NaN,NaN,0.0
29,54.0,startup_1,NaN,"Nov 11, 2018",Current Employee,Anonymous Employee,Amazing,People and culture are terrific,None that I can think of,NaN,5,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74191,66902.0,startup_6,NaN,"Jun 26, 2012",Current Employee,Anonymous Employee,a great company,"In ms, you can always work on the latest techn...",The work is stressful. It is not easy to get t...,Keep focus,3,4,4,3,4,0,NaN
74192,66903.0,startup_6,NaN,"Jun 23, 2012",Former Employee,Legal and Corporate Affairs,Great place to grow and learn from the best in...,"Amazing ressources available, has a global imp...","Microsoft is rather big and bureaucratic, and ...",NaN,3,4,4,5,4,0,NaN
74193,66904.0,startup_6,Hyderabad (India),"Jun 12, 2012",Current Employee,Associate Consultant,Associate Consultant,Very Nice and people friendly company,Projects are not very good,NaN,4,5,4,5,4,0,NaN
74194,66905.0,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,MS review,"Good infrastructure, Work from home, Very tale...",Very competitive environment to work,NaN,5,5,5,5,5,0,NaN
74195,66907.0,startup_6,"Reading, England (UK)","Jun 21, 2012",Current Employee,Technical Lead,Fantastic place to work and develop,"Great set of benefits, flexible working enviro...",Salary is somewhat slightly below market avera...,NaN,5,5,4,3,5,0,NaN
74196,66911.0,startup_6,Hyderabad (India),"Jun 12, 2012",Current Employee,Associate Consultant,Associate Consultant,Very Nice and people friendly company,Projects are not very good,NaN,4,5,4,5,4,0,NaN
74197,66912.0,startup_6,Hyderabad (India),"Jun 14, 2012",Current Employee,Consultant,"Review on Microsoft Global Services, Hyderabad",1. The work culture. 2. The crowd - all the ta...,1. Although the performance management system ...,1. The people managers need to be more focused...,4,5,3,4,3,2,NaN
74198,66913.0,startup_6,NaN,"Jul 2, 2012",Former Employee,Sales Manager,"no job security, unable to see the light at th...",Looks good in your CV,- If you are in 'that' circle - then it is goo...,- Cultivate teamwork and listen.,2,1,2,2,1,7,NaN
74199,66914.0,startup_6,Bengaluru (India),"Jun 12, 2012",Current Employee,Technical Support Engineer,"Great place to work, excellent for technical l...",It's a great place for techies. The kind of te...,Manager favouritism is rampant in the org. Try...,NaN,2,4,2,4,2,2,NaN
74200,66915.0,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,Great company,lots of things to work on and always changing,can be demanding and long hours,NaN,4,4,5,4,4,0,NaN
74201,66923.0,startup_6,Bengaluru (India),"Jun 19, 2012",Current Employee,Consultant,Global Partner Technical Consultant,Leader and very exciting to know the people wh...,There is no flexible timing nor work from home...,Work from home option would be option to many ...,3,4,3,4,4,0,NaN
74202,66928.0,startup_6,Bengaluru (India),"Jun 17, 2012",Current Employee,Technical Support Engineer,It has been a superb experience learning in th...,Values you Great vision Lovely work place Out ...,"With some internal orgs, growth opportunities ...",NaN,3,5,4,4,4,0,NaN
74203,66931.0,startup_6,NaN,"Jun 13, 2012",Current Employee,Anonymous Employee,Learning opportunity good friendly environment,"Friendly environment, Learning Opportunities, ...","Do not have many companies in Lucknow, so one ...",Keep up the good work,4,4,3,2,5,0,NaN
74204,66933.0,startup_6,NaN,"Jun 13, 2012",Current Employee,Anonymous Employee,Microsoft Services,1. One of the best culture. 2. Lots of values ...,1. Some times work life balance is poor,NaN,2,5,5,3,2,0,NaN
74205,66934.0,startup_6,Hyderabad (India),"Jun 14, 2012",Former Employee,Software Development Engineer,Great company to be a part of,Brand name Work environment Flexi timing Chall...,Competition with great talents :),NaN,5,5,3,4,4,0,NaN
74206,66935.0,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,Awesome employer.. wonderful benefits,"Environment, Development opportunities, teams,...","human resource poor, not process driven, servi...",Take a step back from all the priorities/commi...,4,3,5,5,3,0,NaN
74207,66937.0,startup_6,Chennai (India),"Jun 7, 2012",Current Employee,Law Internship,It's not a big one. but a very descent place t...,The Employer is a very friendly and kind perso...,No Salary for the Internees.,NaN,3,3,4,2,4,1,NaN
74208,66938.0,startup_6,"Vancouver, BC (Canada)","Jun 14, 2012",Current Employee,Solution Specialist,"Confusing but good, it's like working for a go...","Good work life balance, and the pay isn't that...",No really a true sales organization and it's a...,Break the company into 4 separate companies an...,5,4,4,4,3,0,NaN
74209,66939.0,startup_6,NaN,"Jun 4, 2012",Former Employee,Sales Manager,"Was a fun place may years ago, but now a grind...",Always changing. Challenging environment. Lots...,Focus on scorecard not balanced. Too many inte...,Need flexibility to drive customer outcomes wh...,2,3,5,4,3,1,NaN
74210,66941.0,startup_6,NaN,"Jun 7, 2012",Current Employee,Anonymous Employee,very good company,"People are smart (but still not enough), polit...",Some people are very political. Innovation is ...,NaN,4,3,3,3,4,0,NaN
74211,66946.0,startup_6,Hyderabad (India),"Jun 1, 2012",Current Employee,Senior Program Manager,MS India,Good preview to latest technologies,bad management and performance evaluation mech...,NaN,4,3,3,3,2,2,NaN
74212,66955.0,startup_6,NaN,"Jun 2, 2012",Current Employee,Anonymous Employee,"Good company, very demanding, and too much use...","Strong financials, good comps, name recognition.","Very demanding, revenue based, global nature d...","Streamline antiquated processes, trim upper ma...",3,3,3,4,3,0,NaN
74213,66956.0,startup_6,Hyderabad (India),"Jun 7, 2012",Current Employee,Software Testing Engineer,It is equivalent to getting MBA at reputed bus...,1. Flexibility 2. Cross functional growth,1. Microsoft has excellent performance managem...,Performance Management Should be robust,5,4,4,4,3,0,NaN
74214,66959.0,startup_6,NaN,"Jun 4, 2012",Current Employee,Solution Specialist,great place to grow!,Great health benefits. Many internal job oppor...,Red Tape. Tough to negotiate internal politics...,NaN,4,4,5,4,4,0,NaN
74215,66960.0,startup_6,Hyderabad (India),"Jun 7, 2012",Current Employee,Software Testing Engineer,It is equivalent to getting MBA at reputed bus...,1. Flexibility 2. Cross functional growth,1. Microsoft has excellent performance managem...,Performance Management Should be robust,5,4,4,4,3,0,NaN
74216,66962.0,startup_6,NaN,"Jun 2, 2012",Current Employee,Anonymous Employee,SDE II,Great place to work. Great career growth path....,Inefficient management structure. Peer pressur...,NaN,3,4,4,4,3,0,NaN
74217,66967.0,startup_6,NaN,"May 29, 2012",Current Employee,Software Development Engineer,Great company for employees,excellent benefits very diverse work environment,the company is not always (especially lately) ...,try and take more risk...,2,4,4,3,3,1,NaN
74218,66977.0,startup_6,NaN,"May 27, 2012",Current Employee,Anonymous Employee,Good place to work,- Smart coworkers - See your products in the n...,- Lots of meetings for engineers - Bureaucratic,Please let us have less meetings,2,5,4,5,3,0,NaN
74219,66978.0,startup_6,NaN,"Jun 8, 2012",Former Employee,Senior Systems Engineer,Terrible,They had great health benefits (no longer im t...,* 14 hour days * no idea how to run a service ...,Learn to excel (no pun intended) and ignore mo...,1,1,1,3,1,3,NaN
74220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df=df.rename(columns = {'train_file.csv':'ID'})

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74221 entries, 0 to 74220
Data columns (total 17 columns):
ID                74218 non-null float64
Place             74220 non-null object
location          38744 non-null object
date              59614 non-null object
status            59614 non-null object
job_title         59614 non-null object
summary           59506 non-null object
positives         59614 non-null object
negatives         59613 non-null object
advice_to_mgmt    33808 non-null object
overall           59614 non-null object
score_1           56424 non-null object
score_2           53561 non-null object
score_3           56449 non-null object
score_4           56415 non-null object
score_5           56154 non-null object
score_6           30363 non-null float64
dtypes: float64(2), object(15)
memory usage: 9.6+ MB

In [19]:
df.nunique()

ID                59613
Place                13
location           1997
date               3542
status                3
job_title          6491
summary           37923
positives         58404
negatives         58383
advice_to_mgmt    31277
overall              11
score_1              15
score_2              11
score_3              15
score_4              15
score_5             100
score_6              66
dtype: int64

In [20]:
df.overall.describe()

count     59614.0
unique       11.0
top           4.0
freq      12705.0
Name: overall, dtype: float64

In [22]:
pp.ProfileReport(df)